spring:
  redis:
    host: ${REDIS_HOST:clustercfg.*****.cache.amazonaws.com}
    port: ${REDIS_PORT:6379}
    username: ${REDIS_USERNAME:dds***}
    password: ${REDIS_PASSWORD:Dds***87}
    ssl: true

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/redis-tester}