spring:
  redis:
    host: ${REDIS_HOST:clustercfg.crm-subsys-dev-redis-replication-01.vbqfxc.apse1.cache.amazonaws.com}
    port: ${REDIS_PORT:6379}
    username: ${REDIS_USERNAME:ddsdevuser}
    password: ${REDIS_PASSWORD:DdsJOODevOm&#987}
    cluster:
      nodes: ${REDIS_NODES:clustercfg.crm-subsys-dev-redis-replication-01.vbqfxc.apse1.cache.amazonaws.com:6379}
    ssl: true
    mode: standalone

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/redis-tester}